services:
  tsukiyomi-bot:
    build: .
    container_name: tsukiyomi-bot
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped
